### ISSUE TITLE
[lately] file share feature needed.

### ISSUE THREAD

**Issue by theun0524** [vmeeting-io/vmeeting_issue#200]
[발생현상]
파일 공유 기능이 없음.
채팅 창에 파일 공유 기능 추가해주세요.

[발생일자]

[재현경로]
- 발생 환경 : 
1. 
2.
3. 

[스크린샷 및 동영상 첨부]

**Comment by sajan-dpnm** [comment]
A prototype implementation of the file sharing feature has been pushed to the Vmeeting implementation in lately. 
![image](https://user-images.githubusercontent.com/72065079/137458199-4c687fd5-3b5f-4266-b39f-1c52470d454e.png)

whereby users can share a file in a chatroom by clicking on the file icon inside the chat input field. Since this is a prototypic implementation that was completed without any explicit specifications. @theun0524 @jungheekang Please address to the following if they are of concerns:

1.  Currently, the feature allows sharing/uploading of all kinds of files. (Images, Videos, PDFs, DOCs, XLS, EXEs and all). Should this feature only allow participants to upload only specific types of files? Or should we continue to allow everyone to upload all kinds of files?
2.  Currently, anyone in the chatroom is allowed to share a file. Should there be a restriction that file-sharing feature should be allowed only for registered users?
3. Should there be a limit on the size of the uploaded files? If yes, please specify the maximum file size allowed for upload. Also, should the feature start a spinner (loading) emoticon or icon during file upload (when the file size is large and file uploaded has not been completed yet)?
4. Uploaded files are segragated based on meeting rooms and stored to the directory $LATELY SERVER$/vmeeting/vmapi/routes/uploads/$MEETING_ROOM_NAME$/. Is there a more appropriate or specific location for the uploaded files to be stored?
5. Currently, the storage lifetime of uploaded files is not defined. Uploaded files occupy the storage unless they are deleted. There are no cron jobs for the removal of the files uploaded to the meeting. Storage of these uploaded files can later cause strain on the server. I think there should be appropriate cron job mechanism for the removal of these files that were uploaded to the server and are not currently in use.
6. We are not using any database tables to track uploaded files. Should there be a database to track uploaded files? I personally think that adding a database table to track uploaded files can further delay the deadline of the required feature. However, since we are not using database table to track uploaded files, how should we uniquely identify uploaded files in the conference? If two files with the same name are uploaded by two different users in the conference, only one is retained in the storage directory. The previous existing file with the same name is overwritten by the new file. Please suggest appropriate way to handle this mechanism.
7. Should the file download link be accessible to everyone with the link or only to registered users?
8. Files are stored “unencrypted” at our server. Are we ok to proceed with it unencrypted ?

@anish9849 please add further questions that you may have had

**Comment by jungheekang** [comment]
@sajan-dpnm  I will answer the questions above.

1. Image, video, audio, document, zip file 
   (Generally, it refers to an extension that is used a lot. Rare extensions do not need to be included.)

2. Please allow all participants to upload

3. Please limit the upload to 300mb

4. Set the storage location at the same level as the meeting recording storage location.

5. First (for the time being), the same as the standard for deleting meeting recorded files, set it to 30 days.

6. Please take care of it so that it can be saved differently even with the same name. It shouldn't be overwritten. (There is also a way to save by adding 1 at the end.)

7. The download is open to all participants.

8. It seems that it does not need to be encrypted in the same way as meeting recordings.

**Comment by jungheekang** [comment]
@sajan-dpnm 
Please implement it like the attached picture.

<img width="306" alt="image" src="https://user-images.githubusercontent.com/87403323/137689412-2935df16-b61e-4471-83ba-3bd51f6abcb7.png">

**Comment by jungheekang** [comment]
@sajan-dpnm  
1. Fixed box width and height
2. word
    eng) Size 
    kor) 용량

**Comment by jungheekang** [comment]
@anish9849 @sajan-dpnm Upload and download should work in the same way in the APP.

**Comment by anish9849** [comment]
@jungheekang It is pretty hard to keep track of tasks if you assign it comments. How about making it a separate issue or use of other platform to keep track of issues and ongoing tasks ?

**Comment by jungheekang** [comment]
@anish9849 Shall we make it a "file share" channel in Slack?

**Comment by anish9849** [comment]
@jungheekang Although I have never used it, I would prefer to try platforms like Jira. The simplest solution would be to create it as a separate issue.  Furthermore, if we decide to stick with github issues, I think we should have some sort of labels signifying the level of urgency of the issue. For e.g., I never knew that File Sharing feature is to be completed by the end of this months until @sajan-dpnm  told me about it this evening.

**Comment by jungheekang** [comment]
@anish9849 The introduction of a new platform or tool will be decided after consulting with Director Eun. And first of all, I will arrange it tomorrow so that it can be managed by adding priority and schedule (milestone) labels on GitHub.

**Comment by anish9849** [comment]
ok.
