### ISSUE TITLE
[lately][func]생일날이되면 적용되면 참가자 목록의 추가액션 메뉴와 음소거 메뉴가 생김

### ISSUE THREAD

**Issue by jungheekang** [vmeeting-io/vmeeting_issue#228]
[발생현상]
생일날이되면 적용되면 참가자 목록의 추가액션 메뉴와 음소거 메뉴가 생김

[발생일자]
2021-11-29

[재현경로]
1. 설정 - 생년월일 - 오늘로 설정
2. 참가자목록 - 생일인 참가자 마우스 오버 시 음소거버튼, 추가액션 버튼 2개 발생됨

[스크린샷 및 동영상 첨부]
<img width="313" alt="스크린샷 2021-11-29 오후 8 04 19" src="https://user-images.githubusercontent.com/87403323/143857100-ccc4a58c-9c8d-4b79-afaf-2308760504ab.png">

**Comment by sajan-dpnm** [comment]
@jungheekang what is the desired functionality that you want in this scenario? only 1 추가액션 button?

**Comment by jungheekang** [comment]
@sajan-dpnm Mute button should not appear on my profile(me).
It is an error that two additional action buttons are displayed.

**Comment by sajan-dpnm** [comment]
@jungheekang  okay, i will remove the Mute button from self profile. But it begs the question again as to whether we want to display the actions (...) button next to the participant. Because as far as I remember, it was Mr. Kang's opinion to allow putting birthday hat by oneself, so if it's the participant's birthday and we decide to remove the actions button then the participant can't put on birthday hat for oneself. If you want to remove the action of applying birthday hat on oneself, then this is not a problem. Please clarify your opinion on this

**Comment by sajan-dpnm** [comment]
@jungheekang 과장님, 제가 이해하는데로 코드 수정하고 lately 에서 push 했습니다. please let me know your opinion

**Comment by jungheekang** [comment]
넵 확인했습니다. 버튼 2개가 나오는 것중 1개만 나오는게 맞습니다.

**Comment by sajan-dpnm** [comment]
okay
